### ISSUE TITLE
need to migrate to P4

### ISSUE THREAD

**Issue by tokkentakker** [tokkentakker/2015-GA-Juniors#38]
![image](https://cloud.githubusercontent.com/assets/6943484/9530596/d4119e10-4cce-11e5-91e7-b2bc661d719f.png)

**Comment by sschneid1** [comment]
Done. I think.
I can't seem to get rid of the extra folders, though. Won't let me remove from workspace.

**Comment by tokkentakker** [comment]
looks like you are able to load in the assigned project.

**Comment by tokkentakker** [comment]
Are they writeable?

On Aug 31, 2015, at 10:22 AM, sschneid1 notifications@github.com wrote:

Done. I think.
I can't seem to get rid of the extra folders, though. Won't let me remove from workspace.
